### ISSUE TITLE
ImportError: No module named 'vulnerabilities'

### ISSUE THREAD

**Issue by izzy** [FallibleInc/retirejslib#1]
When trying to import retirejs after installing it with pip I get the following error:

> Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
> [GCC 5.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import retirejs
> > > > Traceback (most recent call last):
> > > >   File "<stdin>", line 1, in <module>
> > > >   File "/usr/lib/python3.5/site-packages/retirejs/**init**.py", line 2, in <module>
> > > >     from .retirejs import (scan_endpoint,
> > > >   File "/usr/lib/python3.5/site-packages/retirejs/retirejs.py", line 2, in <module>
> > > >     from vulnerabilities import definitions
> > > > ImportError: No module named 'vulnerabilities'

Any ideas on what could cause this?

**Comment by mkagenius** [comment]
Python 3 has syntax change in the way import works. We fixed it. You can update the retirejs version to `1.3`:

`pip install retirejs --upgrade`
